// Generated by CoffeeScript 1.10.0
(function() {
  var BottleneckError,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  BottleneckError = (function(superClass) {
    extend(BottleneckError, superClass);

    function BottleneckError(code, message) {
      this.code = code;
      this.message = message;
      Error.captureStackTrace(this, this);
    }

    return BottleneckError;

  })(Error);

  module.exports = BottleneckError;

}).call(this);
